name: Deploy to Azure Button
author: wilfriedwoivre
description: Add deploy to Azure button to markdown file
branding:
  icon: 'award'  
  color: 'blue'
inputs:
  markdownPath:
    description: 'Path to markdown file to edit'
    required: false
    default: 'README.md'
  templatePath:
    description: 'Path for ARM Template file'
    required: false
    default: 'azuredeploy.json'
  branchName: 
    description: 'Target branch name for deployment'
    required: false
    default: 'master'
outputs:
  fileUpdated: 
    description: 'Boolean if file is updated'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    markdownPath: ${{ inputs.markdownPath }}
    templatePath: ${{ inputs.templatePath }}
    branchName: ${{ inputs.branchName }}
