name: Deploy to Azure Button
author: wilfriedwoivre
description: Add deploy to Azure button to markdown file
branding:
  icon: 'award'  
  color: 'blue'
inputs:
  markdownPath:
    description: 'Path to markdown file to edit'
    required: false
    default: 'README.md'
  templatePath:
    description: 'Path for ARM Template file'
    required: false
    default: 'azuredeploy.json'
outputs:
  fileUpdated: 
    description: 'Boolean if file is updated'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
