name: Deploy to Azure Button
author: wilfriedwoivre
description: Add deploy to Azure button to markdown file
inputs:
  markdownPath:
    description: 'Path to markdown file to edit'
    required: false
    default: 'README.md'
  templatePath:
    description: 'Path for ARM Template file'
    required: false
    default: 'azuredeploy.json'
  githubToken:
    description: 'Github Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.markdownPath }}
    - ${{ inputs.templatePath }}
    - ${{ inputs.githubToken }}
    